# Generated by Django 5.0.7 on 2024-07-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default='2001-04-01'),
            preserve_default=False,
        ),
    ]
