# Generated by Django 5.0.7 on 2024-07-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_customuser_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-from_date']},
        ),
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-from_date']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
