# Generated by Django 5.0.7 on 2024-07-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_achievement_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
