# Generated by Django 5.0.7 on 2024-08-01 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_aditional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aditional',
            options={'ordering': ['-date']},
        ),
    ]
