# Generated by Django 5.0.7 on 2024-08-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_aditional_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aditional',
            new_name='Additional',
        ),
    ]
