# Generated by Django 5.0.7 on 2024-08-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_rename_aditional_additional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additional',
            options={},
        ),
        migrations.RenameField(
            model_name='additional',
            old_name='date',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='additional',
            name='to_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
