# Generated by Django 5.0.7 on 2024-08-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_alter_additional_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additional',
            options={'ordering': ['-from_date']},
        ),
    ]
